# Generated by Django 4.0.3 on 2022-04-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand'),
        ),
    ]
