# Generated by Django 4.0.3 on 2022-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_project_review_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('podcastlink', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
